- hosts: "{{host_group_name | default('localhost')}}"
  connection: local

  tasks:
  - name: debug hosts
    debug:
      msg: "{{ groups['all'] }}"
  - name: debug passed group name
    debug:
      msg: "{{ host_group_name }}"
